### Sales Data

### Problem Statement
The retail company is preparing its monthly sales performance report, but the raw sales data contains missing values, duplicate records, inconsistent formats, incorrect data types, invalid numerical values, and potentially incorrect Sales and Profit values. If these issues are not resolved before analysis, management may make decisions using inaccurate revenue, profitability, product, regional, and salesperson information. Your task is to act as a Data Analyst and convert the raw sales file into a reliable, consistent, and analysis-ready dataset that can be safely used for reporting and future EDA.

### Objective of the Data
1. Data Loading & Initial Inspection
2. Missing Values & Blank Data
3. Duplicate Records & Order IDs
4. Data Type & Format Correction
5. Text Standardization
6. Invalid Value Detection
7. Business Rule Validation
8. Create the Cleaned Dataset
9.  Final Data Quality Validation
10. Export & Document the Result

In [ ]:
Data Loading & Initial Inspection — Load the raw CSV into Pandas and inspect its shape, columns, sample records, data types, and overall structure.
2. Missing Values & Blank Data — Identify missing values, empty strings, and whitespace-only values, then determine an appropriate treatment for each affected field.
3. Duplicate Records & Order IDs — Detect exact duplicate rows and duplicate Order_ID values, investigate the affected records, and decide which records should remain.
4. Data Type & Format Correction — Correct incorrect or mixed data types and standardize Order_Date, Quantity, Unit_Price, Discount, Sales, and Profit into appropriate formats.
5. Text Standardization — Clean and standardize Region, Product, Category, and Salesperson values by handling spaces, capitalization differences, and inconsistent labels.
6. Invalid Value Detection — Identify negative, impossible, or out-of-range values in Quantity, Unit_Price, Discount, Sales, and Profit and decide how each issue should be resolved.
7. Business Rule Validation — Check whether Sales is logically consistent with Quantity, Unit_Price, and Discount, and investigate suspicious Profit values using an appropriate business rule.
8. Create the Cleaned Dataset — Apply all justified cleaning decisions to a copy of the raw dataframe while preserving the original raw CSV unchanged.
9. Final Data Quality Validation — Recheck missing values, duplicates, data types, invalid values, unique Order_IDs, and category consistency to confirm that the cleaned dataset is analysis-ready.
10. Export & Document the Result — Save the final dataset as Sales Data Cleaned.csv and prepare a concise before-versus-after data-quality summary documenting the major corrections.

### Import Libraries

In [7]:
pip install numpy pandas matplotlib seaborn

Requirement already satisfied: numpy in .\venv\Lib\site-packages (2.5.3)
Requirement already satisfied: pandas in .\venv\Lib\site-packages (3.0.6)
Requirement already satisfied: matplotlib in .\venv\Lib\site-packages (3.11.2)
Requirement already satisfied: seaborn in .\venv\Lib\site-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in .\venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\venv\Lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: contourpy>=1.0.1 in .\venv\Lib\site-packages (from matplotlib) (1.4.0)
Requirement already satisfied: cycler>=0.10 in .\venv\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in .\venv\Lib\site-packages (from matplotlib) (4.66.1)
Requirement already satisfied: kiwisolver>=1.3.1 in .\venv\Lib\site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: packaging>=20.0 in .\venv\Lib\site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in .\venv\Lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in .\venv\Lib\site-packages (from matplotlib) (3.3.3)
Requirement already satisfied: six>=1.5 in .\venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

### Import Modules

In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Load Dataset

In [4]:
import pandas as pd

data = pd.read_csv("Sales Data Cleaning Task.csv")

print(data.shape)
print(data.head())
print(data.columns)

(121, 11)
  Order_ID Order_Date Region     Product     Category Quantity Unit_Price  \
0    S0001   01-27-26  North  Smartphone  Electronics      1.0    28000.0
1    S0002   06-04-26  North      Laptop  Electronics      1.0    55000.0
2    S0003   01-02-26  South      Tablet  Electronics      4.0    22000.0
3    S0004   03-28-26  North       Mouse  Accessories      5.0      400.0
4    S0005   01-12-26   West      Tablet  Electronics      2.0    22000.0

   Discount    Sales   Profit Salesperson
0      0.05  26600.0  3137.36       Vijay
1      0.05  52250.0  6246.61       Divya
2      0.20  70400.0  8961.39       Vijay
3      0.05   1900.0   461.18       Priya
4      0.10  39600.0  7232.28       Priya
Index(['Order_ID', 'Order_Date', 'Region', 'Product', 'Category', 'Quantity',
       'Unit_Price', 'Discount', 'Sales', 'Profit', 'Salesperson'],
      dtype='str')

### Verify The Dataset

In [5]:
print("Dataset Load Successfully")
print(data.shape[0])
print(data.shape[1])

Dataset Load Successfully
121
11

### Inspect Dataset

In [9]:
print("Shape:", data.shape)

print("\nColumns:")
print(data.columns)

print("\nData types:")
print(data.dtypes)

print("\nDuplicate row:")
print(data.duplicated().sum())

print("\nSummary:")
print(data.describe(include="all"))

Shape: (121, 11)

Columns:
Index(['Order_ID', 'Order_Date', 'Region', 'Product', 'Category', 'Quantity',
       'Unit_Price', 'Discount', 'Sales', 'Profit', 'Salesperson'],
      dtype='str')

Data types:
Order_ID           str
Order_Date         str
Region             str
Product            str
Category           str
Quantity           str
Unit_Price         str
Discount       float64
Sales          float64
Profit         float64
Salesperson        str
dtype: object

Duplicate row:
2

Summary:
       Order_ID Order_Date Region Product     Category Quantity Unit_Price  \
count       120        119    118     119          120      119        119
unique      118         88      7      10            4       11         25
top       S0021   05-22-26  South  Tablet  Electronics      5.0    22000.0
freq          2          5     34      22           70       20         12
mean        NaN        NaN    NaN     NaN          NaN      NaN        NaN
std         NaN        NaN    NaN     NaN          NaN      NaN        NaN
min         NaN        NaN    NaN     NaN          NaN      NaN        NaN
25%         NaN        NaN    NaN     NaN          NaN      NaN        NaN
50%         NaN        NaN    NaN     NaN          NaN      NaN        NaN
75%         NaN        NaN    NaN     NaN          NaN      NaN        NaN
max         NaN        NaN    NaN     NaN          NaN      NaN        NaN

          Discount          Sales         Profit Salesperson
count   120.000000     119.000000     119.000000         118
unique         NaN            NaN            NaN           9
top            NaN            NaN            NaN       Priya
freq           NaN            NaN            NaN          23
mean      0.115417   69444.970588   12513.385462         NaN
std       0.122096   87541.325798   19079.163458         NaN
min       0.000000  -15000.000000   -3000.000000         NaN
25%       0.050000    6545.000000    1136.180000         NaN
50%       0.100000   40800.000000    5509.340000         NaN
75%       0.150000   90600.000000   13896.485000         NaN
max       1.250000  496000.000000  120692.880000         NaN

### Standardize Column Names

In [12]:
df =data.copy()
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ","_")
)
print(df.columns)

Index(['order_id', 'order_date', 'region', 'product', 'category', 'quantity',
       'unit_price', 'discount', 'sales', 'profit', 'salesperson'],
      dtype='str')

### Clean Text Columns

In [24]:
text_cols = ["Region", "Product", "Category", "Salesperson"]

for col in text_cols:
    data[col] = data[col].astype("string").str.strip()
    print(data)

    Order_ID Order_Date Region     Product     Category Quantity Unit_Price  \
0      S0001   01-27-26  North  Smartphone  Electronics      1.0    28000.0
1      S0002   06-04-26  North      Laptop  Electronics      1.0    55000.0
2      S0003   01-02-26  South      Tablet  Electronics      4.0    22000.0
3      S0004   03-28-26  North       Mouse  Accessories      5.0      400.0
4      S0005   01-12-26   West      Tablet  Electronics      2.0    22000.0
..       ...        ...    ...         ...          ...      ...        ...
116    S0117   05-05-26  North  Smartphone  Electronics      6.0    35000.0
117    S0118   01-26-26  North     Monitor  Electronics      5.0    12000.0
118    S0119   01-15-26   East  Headphones  Accessories      5.0     1200.0
119    S0046   02-26-26  South  Headphones  Accessories      2.0     3200.0
120      NaN        NaN   <NA>        <NA>         <NA>      NaN        NaN

     Discount     Sales   Profit Salesperson
0        0.05   26600.0  3137.36       Vijay
1        0.05   52250.0  6246.61       Divya
2        0.20   70400.0  8961.39       Vijay
3        0.05    1900.0   461.18       Priya
4        0.10   39600.0  7232.28       Priya
..        ...       ...      ...         ...
116      0.10  189000.0 -3000.00       Priya
117      0.00   60000.0  9226.51       Meena
118      0.00    6000.0   810.86       Sneha
119      0.00    6400.0  1446.15       Meena
120       NaN       NaN      NaN        <NA>

[121 rows x 11 columns]
    Order_ID Order_Date Region     Product     Category Quantity Unit_Price  \
0      S0001   01-27-26  North  Smartphone  Electronics      1.0    28000.0
1      S0002   06-04-26  North      Laptop  Electronics      1.0    55000.0
2      S0003   01-02-26  South      Tablet  Electronics      4.0    22000.0
3      S0004   03-28-26  North       Mouse  Accessories      5.0      400.0
4      S0005   01-12-26   West      Tablet  Electronics      2.0    22000.0
..       ...        ...    ...         ...          ...      ...        ...
116    S0117   05-05-26  North  Smartphone  Electronics      6.0    35000.0
117    S0118   01-26-26  North     Monitor  Electronics      5.0    12000.0
118    S0119   01-15-26   East  Headphones  Accessories      5.0     1200.0
119    S0046   02-26-26  South  Headphones  Accessories      2.0     3200.0
120      NaN        NaN   <NA>        <NA>         <NA>      NaN        NaN

     Discount     Sales   Profit Salesperson
0        0.05   26600.0  3137.36       Vijay
1        0.05   52250.0  6246.61       Divya
2        0.20   70400.0  8961.39       Vijay
3        0.05    1900.0   461.18       Priya
4        0.10   39600.0  7232.28       Priya
..        ...       ...      ...         ...
116      0.10  189000.0 -3000.00       Priya
117      0.00   60000.0  9226.51       Meena
118      0.00    6000.0   810.86       Sneha
119      0.00    6400.0  1446.15       Meena
120       NaN       NaN      NaN        <NA>

[121 rows x 11 columns]
    Order_ID Order_Date Region     Product     Category Quantity Unit_Price  \
0      S0001   01-27-26  North  Smartphone  Electronics      1.0    28000.0
1      S0002   06-04-26  North      Laptop  Electronics      1.0    55000.0
2      S0003   01-02-26  South      Tablet  Electronics      4.0    22000.0
3      S0004   03-28-26  North       Mouse  Accessories      5.0      400.0
4      S0005   01-12-26   West      Tablet  Electronics      2.0    22000.0
..       ...        ...    ...         ...          ...      ...        ...
116    S0117   05-05-26  North  Smartphone  Electronics      6.0    35000.0
117    S0118   01-26-26  North     Monitor  Electronics      5.0    12000.0
118    S0119   01-15-26   East  Headphones  Accessories      5.0     1200.0
119    S0046   02-26-26  South  Headphones  Accessories      2.0     3200.0
120      NaN        NaN   <NA>        <NA>         <NA>      NaN        NaN

     Discount     Sales   Profit Salesperson
0        0.05   26600.0  3137.36       Vijay
1        0.05   52250.0  6246.61       Divya
2        0.20   70400.0  8961.39       Vijay
3        0.05    1900.0   461.18       Priya
4        0.10   39600.0  7232.28       Priya
..        ...       ...      ...         ...
116      0.10  189000.0 -3000.00       Priya
117      0.00   60000.0  9226.51       Meena
118      0.00    6000.0   810.86       Sneha
119      0.00    6400.0  1446.15       Meena
120       NaN       NaN      NaN        <NA>

[121 rows x 11 columns]
    Order_ID Order_Date Region     Product     Category Quantity Unit_Price  \
0      S0001   01-27-26  North  Smartphone  Electronics      1.0    28000.0
1      S0002   06-04-26  North      Laptop  Electronics      1.0    55000.0
2      S0003   01-02-26  South      Tablet  Electronics      4.0    22000.0
3      S0004   03-28-26  North       Mouse  Accessories      5.0      400.0
4      S0005   01-12-26   West      Tablet  Electronics      2.0    22000.0
..       ...        ...    ...         ...          ...      ...        ...
116    S0117   05-05-26  North  Smartphone  Electronics      6.0    35000.0
117    S0118   01-26-26  North     Monitor  Electronics      5.0    12000.0
118    S0119   01-15-26   East  Headphones  Accessories      5.0     1200.0
119    S0046   02-26-26  South  Headphones  Accessories      2.0     3200.0
120      NaN        NaN   <NA>        <NA>         <NA>      NaN        NaN

     Discount     Sales   Profit Salesperson
0        0.05   26600.0  3137.36       Vijay
1        0.05   52250.0  6246.61       Divya
2        0.20   70400.0  8961.39       Vijay
3        0.05    1900.0   461.18       Priya
4        0.10   39600.0  7232.28       Priya
..        ...       ...      ...         ...
116      0.10  189000.0 -3000.00       Priya
117      0.00   60000.0  9226.51       Meena
118      0.00    6000.0   810.86       Sneha
119      0.00    6400.0  1446.15       Meena
120       NaN       NaN      NaN        <NA>

[121 rows x 11 columns]

### Invalid Quantity Values

In [31]:
print(df.columns)

Index(['order_id', 'order_date', 'region', 'product', 'category', 'quantity',
       'unit_price', 'discount', 'sales', 'profit', 'salesperson'],
      dtype='str')

### Validate Sales Calculation

In [34]:
quantity = 5
unit_price = 1000
discount = 0.10

sales = quantity * unit_price * (1 - discount)

print(sales)

4500.0

### Create Cleaned Dataset

In [35]:
cleaned_data = df.copy()

In [36]:
cleaned_data = df.copy()

print("Cleaned dataset copy created successfully!")

Cleaned dataset copy created successfully!

### Final Data Quality Validation

In [37]:
cleaned_data.isnull().sum()

order_id       1
order_date     2
region         3
product        2
category       1
quantity       2
unit_price     2
discount       1
sales          2
profit         2
salesperson    3
dtype: int64

### Missing Values & Blank Data

In [38]:
cleaned_data.duplicated().sum()

np.int64(2)

In [42]:
print(cleaned_data.columns)
cleaned_data["order_id"].duplicated().sum()

Index(['order_id', 'order_date', 'region', 'product', 'category', 'quantity',
       'unit_price', 'discount', 'sales', 'profit', 'salesperson'],
      dtype='str')

np.int64(2)

In [43]:
cleaned_data[cleaned_data["order_id"].duplicated(keep=False)]

,order_id,order_date,region,product,category,quantity,unit_price,discount,sales,profit,salesperson
20,S0021,05-22-26,South,Monitor,Electronics,4.0,9000.0,0.1,32400.0,2707.86,Divya
45,S0046,02-26-26,South,Headphones,Accessories,2.0,3200.0,0.0,6400.0,1446.15,Meena
115,S0021,05-22-26,South,Monitor,Electronics,4.0,9000.0,0.1,32400.0,2707.86,Divya
119,S0046,02-26-26,South,Headphones,Accessories,2.0,3200.0,0.0,6400.0,1446.15,Meena

In [44]:
cleaned_data = cleaned_data.drop_duplicates()
cleaned_data.duplicated().sum()

np.int64(0)

### Data Type & Format Correction

In [45]:
cleaned_data.dtypes

order_id           str
order_date         str
region             str
product            str
category           str
quantity           str
unit_price         str
discount       float64
sales          float64
profit         float64
salesperson        str
dtype: object

In [46]:
cleaned_data.isnull().sum()

order_id       1
order_date     2
region         3
product        2
category       1
quantity       2
unit_price     2
discount       1
sales          2
profit         2
salesperson    3
dtype: int64

In [47]:
cleaned_data[cleaned_data.isnull().any(axis=1)]

,order_id,order_date,region,product,category,quantity,unit_price,discount,sales,profit,salesperson
7,S0008,04-01-26,NaN,Keyboard,Accessories,8.0,1600.0,0.10,11520.0,1240.14,Rahul
18,S0019,04-19-26,South,NaN,Wearables,3.0,8000.0,0.20,19200.0,4383.62,Divya
29,S0030,05-05-26,South,Keyboard,Accessories,NaN,1600.0,0.20,8960.0,1724.96,Divya
44,S0045,04-16-26,South,Tablet,Electronics,1.0,NaN,0.10,13500.0,2875.58,Rahul
52,S0053,05-22-26,NaN,Keyboard,Accessories,7.0,1100.0,0.15,6545.0,1299.35,Divya
57,S0058,01-19-26,West,Laptop,Electronics,4.0,72000.0,0.20,NaN,51714.53,Vijay
73,S0074,04-30-26,East,Headphones,Accessories,8.0,1200.0,0.20,7680.0,NaN,Sneha
91,S0092,04-17-26,South,Headphones,Accessories,5.0,1200.0,0.05,5700.0,570.78,NaN
105,S0106,NaN,West,Monitor,Electronics,5.0,12000.0,0.10,54000.0,8341.91,Priya
108,S0109,05-22-26,South,Keyboard,Accessories,7.0,1100.0,0.15,6545.0,794.79,NaN
120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
cleaned_data.loc[cleaned_data["order_id"].isnull()]

,order_id,order_date,region,product,category,quantity,unit_price,discount,sales,profit,salesperson
120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
cleaned_data.loc[[7, 18, 29, 30, 45, 53, 58, 73, 91, 105, 108]]

,order_id,order_date,region,product,category,quantity,unit_price,discount,sales,profit,salesperson
7,S0008,04-01-26,NaN,Keyboard,Accessories,8.0,1600.0,0.10,11520.0,1240.14,Rahul
18,S0019,04-19-26,South,NaN,Wearables,3.0,8000.0,0.20,19200.0,4383.62,Divya
29,S0030,05-05-26,South,Keyboard,Accessories,NaN,1600.0,0.20,8960.0,1724.96,Divya
30,S0031,01-16-26,East,Keyboard,Accessories,4.0,700.0,0.20,2240.0,459.37,Arun
45,S0046,02-26-26,South,Headphones,Accessories,2.0,3200.0,0.00,6400.0,1446.15,Meena
53,S0054,03-19-26,West,Tablet,Electronics,7.0,30000.0,0.05,199500.0,36835.19,Arun
58,S0059,06-17-26,North,Monitor,Electronics,7.0,18000.0,0.15,107100.0,13010.22,Priya
73,S0074,04-30-26,East,Headphones,Accessories,8.0,1200.0,0.20,7680.0,NaN,Sneha
91,S0092,04-17-26,South,Headphones,Accessories,5.0,1200.0,0.05,5700.0,570.78,NaN
105,S0106,NaN,West,Monitor,Electronics,5.0,12000.0,0.10,54000.0,8341.91,Priya
108,S0109,05-22-26,South,Keyboard,Accessories,7.0,1100.0,0.15,6545.0,794.79,NaN

In [50]:
cleaned_data.dtypes

order_id           str
order_date         str
region             str
product            str
category           str
quantity           str
unit_price         str
discount       float64
sales          float64
profit         float64
salesperson        str
dtype: object

### Business Rule Validation

In [52]:
cleaned_data[["quantity", "unit_price", "discount", "sales", "profit"]].dtypes

quantity          str
unit_price        str
discount      float64
sales         float64
profit        float64
dtype: object

### Create the Cleaned Dataset

In [54]:
cleaned_data["quantity"] = pd.to_numeric(cleaned_data["quantity"], errors="coerce")
cleaned_data["unit_price"] = pd.to_numeric(cleaned_data["unit_price"], errors="coerce")
cleaned_data[["quantity", "unit_price"]].dtypes

quantity      float64
unit_price    float64
dtype: object

In [55]:
cleaned_data[
    (cleaned_data["quantity"] < 0) |
    (cleaned_data["unit_price"] < 0) |
    (cleaned_data["discount"] < 0) |
    (cleaned_data["discount"] > 1) |
    (cleaned_data["sales"] < 0)
]

,order_id,order_date,region,product,category,quantity,unit_price,discount,sales,profit,salesperson
31,S0032,01-21-26,South,Laptop,Electronics,-2.0,62000.0,0.00,496000.0,120692.88,Priya
54,S0055,06-05-26,East,Keyboard,Accessories,5.0,-5000.0,0.15,2975.0,635.40,Meena
76,S0077,04-20-26,East,Keyboard,Accessories,2.0,1600.0,1.25,3200.0,444.88,Priya
110,S0111,06-18-26,West,Laptop,Electronics,5.0,68000.0,0.20,-15000.0,48575.66,Karthik

cleaned_data.loc[[31, 54, 76, 110]]

In [57]:
for i in [54, 76, 110]:
    row = cleaned_data.loc[i]
    print(
        row["order_id"],
        row["quantity"] * row["unit_price"] * (1 - row["discount"])
    )

S0055 -21250.0
S0077 -800.0
S0111 272000.0

In [60]:
cleaned_data.loc[31, "quantity"] = 8
cleaned_data.loc[54, "unit_price"] = 700
cleaned_data.loc[76, "discount"] = 0
cleaned_data.loc[110, "sales"] = 272000
cleaned_data.loc[[31, 54, 76, 110]]

,order_id,order_date,region,product,category,quantity,unit_price,discount,sales,profit,salesperson
31,S0032,01-21-26,South,Laptop,Electronics,8.0,62000.0,0.00,496000.0,120692.88,Priya
54,S0055,06-05-26,East,Keyboard,Accessories,5.0,700.0,0.15,2975.0,635.40,Meena
76,S0077,04-20-26,East,Keyboard,Accessories,2.0,1600.0,0.00,3200.0,444.88,Priya
110,S0111,06-18-26,West,Laptop,Electronics,5.0,68000.0,0.20,272000.0,48575.66,Karthik

In [61]:
cleaned_data[
    (cleaned_data["quantity"] < 0) |
    (cleaned_data["unit_price"] < 0) |
    (cleaned_data["discount"] < 0) |
    (cleaned_data["discount"] > 1) |
    (cleaned_data["sales"] < 0)
]

Empty DataFrame
Columns: [order_id, order_date, region, product, category, quantity, unit_price, discount, sales, profit, salesperson]
Index: []

In [62]:
cleaned_data["calculated_sales"] = (
    cleaned_data["quantity"]
    * cleaned_data["unit_price"]
    * (1 - cleaned_data["discount"])
)

cleaned_data[
    abs(cleaned_data["sales"] - cleaned_data["calculated_sales"]) > 0.01
][["order_id", "quantity", "unit_price", "discount", "sales", "calculated_sales"]]

    order_id  quantity  unit_price  discount    sales  calculated_sales
39     S0040       1.0       700.0      0.15  99999.0             595.0
82     S0083       2.0     12000.0      0.15  24500.0           20400.0
112    S0113       4.0       900.0      0.05    500.0            3420.0

In [63]:
cleaned_data[cleaned_data["order_id"] == "S0040"]

,order_id,order_date,region,product,category,quantity,unit_price,discount,sales,profit,salesperson,calculated_sales
39,S0040,01-12-26,North,Keyboard,Accessories,1.0,700.0,0.15,99999.0,131.49,Sneha,595.0

In [66]:
cleaned_data[cleaned_data["order_id"] == "S0040"]
cleaned_data[cleaned_data["order_id"] == "S0083"]

,order_id,order_date,region,product,category,quantity,unit_price,discount,sales,profit,salesperson,calculated_sales
82,S0083,03-03-26,West,Monitor,Electronics,2.0,12000.0,0.15,24500.0,3326.39,Meena,20400.0

In [68]:
cleaned_data.loc[112]

order_id                  S0113
order_date             03-01-26
region                     West
product                   Mouse
category            Accessories
quantity                    4.0
unit_price                900.0
discount                   0.05
sales                     500.0
profit                   606.04
salesperson                Arun
calculated_sales         3420.0
Name: 112, dtype: object

In [70]:
cleaned_data.loc[cleaned_data["order_id"] == "S0113", "sales"] = 3420
cleaned_data.loc[cleaned_data["order_id"] == "S0113", ["order_id", "sales", "calculated_sales"]]

    order_id   sales  calculated_sales
112    S0113  3420.0            3420.0

In [71]:

cleaned_data[
    abs(cleaned_data["sales"] - cleaned_data["calculated_sales"]) > 0.01
][["order_id", "sales", "calculated_sales"]]

   order_id    sales  calculated_sales
82    S0083  24500.0           20400.0

In [72]:
cleaned_data.loc[82]

order_id                  S0083
order_date             03-03-26
region                     West
product                 Monitor
category            Electronics
quantity                    2.0
unit_price              12000.0
discount                   0.15
sales                   24500.0
profit                  3326.39
salesperson               Meena
calculated_sales        20400.0
Name: 82, dtype: object

In [74]:
cleaned_data.loc[cleaned_data["order_id"] == "S0083", "sales"] = 20400
cleaned_data[
    abs(cleaned_data["sales"] - cleaned_data["calculated_sales"]) > 0.01
][["order_id", "sales", "calculated_sales"]]

Empty DataFrame
Columns: [order_id, sales, calculated_sales]
Index: []

In [75]:
abs(cleaned_data["sales"] - cleaned_data["calculated_sales"]) > 0.01

0      False
1      False
2      False
3      False
4      False
       ...
114    False
116    False
117    False
118    False
120    False
Length: 119, dtype: bool

### Final Data Quality Validation

In [76]:
cleaned_data[
    abs(cleaned_data["sales"] - cleaned_data["calculated_sales"]) > 0.01
]

Empty DataFrame
Columns: [order_id, order_date, region, product, category, quantity, unit_price, discount, sales, profit, salesperson, calculated_sales]
Index: []

In [77]:
cleaned_data.isnull().sum()

order_id            1
order_date          2
region              3
product             2
category            1
quantity            4
unit_price          3
discount            1
sales               2
profit              2
salesperson         3
calculated_sales    6
dtype: int64

In [78]:
cleaned_data["order_id"].duplicated().sum()

np.int64(0)

In [79]:
cleaned_data.dtypes

order_id                str
order_date              str
region                  str
product                 str
category                str
quantity            float64
unit_price          float64
discount            float64
sales               float64
profit              float64
salesperson             str
calculated_sales    float64
dtype: object

In [80]:
cleaned_data[
    (cleaned_data["quantity"] < 0) |
    (cleaned_data["unit_price"] < 0) |
    (cleaned_data["discount"] < 0) |
    (cleaned_data["discount"] > 1) |
    (cleaned_data["sales"] < 0)
]

Empty DataFrame
Columns: [order_id, order_date, region, product, category, quantity, unit_price, discount, sales, profit, salesperson, calculated_sales]
Index: []

In [81]:
for col in ["region", "product", "category", "salesperson"]:
    print(col, cleaned_data[col].astype("string").str.strip().eq("").sum())

region 0
product 1
category 0
salesperson 0

In [82]:
cleaned_data[cleaned_data["product"].isna()]

,order_id,order_date,region,product,category,quantity,unit_price,discount,sales,profit,salesperson,calculated_sales
18,S0019,04-19-26,South,NaN,Wearables,3.0,8000.0,0.2,19200.0,4383.62,Divya,19200.0
120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Export & Document the Result

In [83]:
cleaned_data = cleaned_data.dropna(how="all").reset_index(drop=True)

In [88]:

cleaned_data.to_csv("Sales Data Cleaned.csv", index=False)
import os

print(os.path.exists("Sales Data Cleaned.csv"))

True